spring:
  web:
    resources:
      static-locations: "classpath:/static/"

  datasource:
    username: ${MYSQL_DB_USER}  # set MYSQL username
    password: ${MYSQL_DB_PWD}   # set MYSQL password
    url: jdbc:mysql://localhost:3306/ChatGPTWeb?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

gpt:
  url: https://api.openai.com/v1/chat/completions  #https://platform.openai.com/docs/models/model-endpoint-compatibility
  api-key: ${API_KEY}  # set your api-key  https://platform.openai.com/account/api-keys
  model: gpt-3.5-turbo
  proxy: true
  proxy-port: 7890

